### PR TITLE
common&imxrt106x: reset CFLAGS; some changes after shellcheck

### PR DESCRIPTION
**Pull request by HBuczynski**

### CODE REVIEW

**Comment by nalajcie** [comment]
I don't know if this is the best PR to do it but I remember You've been telling that `CFLAGS` are being duplicated due to being defined 2 times. Maybe we can add the `KERNEL/DEVICE_CFLAGS` to `USER_CFLAGS` and make the changes in `Makefile.common`:
 - reset `CFLAGS` at the beginning
 - append `USER_CFLAGS` at the end (preferably after `Makefile.$(TARGET_SUFF)` to be able to overwrite some of the options set by default) - I don't know why this file is not explicitly included by `Makefile.common`, it's common sense to do it that way (hehe, pun intended)
 - as the second '-' is not possible right now (without changing Makefiles in other repos) - if You don't want to add additional work just add them at the end of `CFLAGS` defined in `Makefile.common` for now

Side note:
 - removing "clean" target is on my TODO list, right now it's not needed anywhere apart from the PORTS. You may add quotes around it, but I hope we will remove it in the near future.

I haven't set up the CI for this repo which might come really handy while doing changes in build system. Let me add it quickly here, maybe we could test Your PR that way (that might involve force-pushing some dummy changes to trigger the CI after the workflow setup).

**Comment by nalajcie** [comment]
please rebase Your PR on top of current `master`, it should trigger the checks

**Comment by nalajcie** [comment]
HA! Another good usage for CI! :+1: 

`TARGET_SUBFAMILY` actually includes `TARGET_FAMILY` in it - so the first commit is invalid:

https://github.com/phoenix-rtos/phoenix-rtos-project/blob/3338c85ba655f8645b5cc58635d6f6a9666ff77a/build.project#L34

**Comment by HBuczynski** [comment]
@nalajcie I was talking about this bug yesterday. 
Firstly I wanted to push changes to submodules of `phoenix-rtos-project` and after that add changes to `phoenix-rtos-project` and update submodules to the newest versions.

**Comment by HBuczynski** [comment]
`CFLAGS` are duplicated in two locations:

- https://github.com/phoenix-rtos/phoenix-rtos-build/blob/ea91c61e8196c3dd8ae2c58f4767d154daacdd07/Makefile.armv7m#L24-L26

- https://github.com/phoenix-rtos/phoenix-rtos-project/blob/3338c85ba655f8645b5cc58635d6f6a9666ff77a/_targets/build.project.armv7m7-imxrt106x#L12-L13

'KERNEL/DEVICE_CFLAGS' were used in the previous build system and are related only to peripherals configuration. I think that these variables shouldn't be set in `Makefile.$(TARGET_SUFF)` or `Makefile.common`. These variables should be specified in build.project file which will not be uploaded to the public repository.

**Comment by pawelpisarczyk** [comment]
Please don't merge this PR. This is not a good idea to provide CFLAGS using this method. We agreed that we provide special target in the Makefile to provide CFLAGS to shell scritps.

**Comment by pawelpisarczyk** [comment]
Moreover, only one CFLAGS definition should be used. Please don't define other variables containing CFLAGS because such approach is chaotic. If you need some specific flags to compile the particular driver please use the basic CFLAGS from Makefile.common and complement them in particular Makefile. I think that differences in CFLAGS exist mostly (or only) in the linking target.

**Comment by nalajcie** [comment]
> Moreover, only one CFLAGS definition should be used. Please don't define other variables containing CFLAGS because such approach is chaotic. If you need some specific flags to compile the particular driver please use the basic CFLAGS from Makefile.common and complement them in particular Makefile. I think that differences in CFLAGS exist mostly (or only) in the linking target.

Yes, that's why I proposed to add `CFLAGS :=` at the beginning of `Makefile.common` (to not pollute the `CFLAGS` from outside of Makefiles).

Regarding the `KERNEL_CFLAGS` - they are not actually `CFLAGS`, they are defines being used in the kernel code (the same for devices), I think @pawelpisarczyk suggestion to directly add them in `phoenix-rtos-devices/Makefile` instead of in shell script is better. I hope they will evolve into separate ENV variables from which appropriate defines would be constructed (that way defines used for UART driver could hopefully be added only to UART compilation, instead of all devices compilation).

**Comment by nalajcie** [comment]
Please either squash or rewrite/abandon commits 13101a7 and 64e30c9 - they cancel each other (apart from shellcheck fixes) so we don't need them in the master branch history.

**Review by nalajcie — APPROVED** [review]

**Pull request merged**
