### PR TITLE
armv7a: split FPU settings for imx6ull and zynq7000

### PR DESCRIPTION
**Pull request by HBuczynski**
## Description

Fixes: phoenix-rtos/phoenix-rtos-project#402

PD-274

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by agkaminski — APPROVED** [review]

**Comment by HBuczynski** [comment]
@damianloew, please verify whether this solution solves the mentioned issue

**Comment by damianloew** [comment]
> @damianloew, please verify whether this solution solves the mentioned issue

Yes, with this change the problem doesn't occur.

**Comment by nalajcie** [comment]
rule of thumb - don't use tabs for indentation in Makefiles (TAB is used as a default recipe prefix which might result in strange errors - especially when including Makefiles in other Makefiles).

Double spaces (`  `) are being used as an indentation in most other places.

**Comment by HBuczynski** [comment]
> rule of thumb - don't use tabs for indentation in Makefiles (TAB is used as a default recipe prefix which might result in strange errors - especially when including Makefiles in other Makefiles).
> 
> Double spaces (` `) are being used as an indentation in most other places.

Ok. The next time I will use double spaces.

**Pull request merged**
