### PR TITLE
Fix mkimg on MacOS

### PR DESCRIPTION
**Pull request by MaciejPurski**
Substitute non-portable `stat -c` with `wc -c`.

### CODE REVIEW

**Comment by nalajcie** [comment]
uch, that's a shame `stat` is not available on Darwin... as `stat` uses `fstat` syscall (so doesn't read the file contents, just the metadata). That's why I'm voting for using `docker` for compilation (to have repeatable environment on all OSes).

Other than that, the change seems to be ok (the building passes on linux/docker) but I haven't checked if it actually runs :).

**Review by nalajcie — APPROVED** [review]

**Comment by MaciejPurski** [comment]
> uch, that's a shame `stat` is not available on Darwin... as `stat` uses `fstat` syscall (so doesn't read the file contents, just the metadata). That's why I'm voting for using `docker` for compilation (to have repeatable environment on all OSes).
@nalajcie, we have discussed this issue earlier in phoenix-rtos-project:
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/40
`stat` is available on Darwin, but uses different parameters, so Linux `stat -c "%s"` is equivalent to Darwin `stat -f "%z"`. An alternative solution, which used `stat`, was proposed by @kemonats. But we have decided that @gerard5  solution with `wc` was simpler.

**Comment by kemonats** [comment]
`stat` is available on `BSD` ( on `Darwin`, I think, too ) but uses the `-f %z` option instead of `-c %s`.

command `wc -c file` also uses `fstat`, but then out is that:
`size file_name`

**Comment by agkaminski** [comment]
So maybe we should do `wc -c filename | cut -f1 -d" "`?

**Pull request merged**
