### PR TITLE
makes: switch to linking by gcc

### PR DESCRIPTION
**Pull request by nalajcie**
CI to pass: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/834

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by agkaminski — APPROVED** [review]

**Comment by nalajcie** [comment]
Just some notes to consider:
 - I'm not sure we should change `LD := gcc ` or just use `$(CC)` in linking commands (both do have advantages and disadvantages)
 - overall the per-target Makefile is much simpler
 - `LDFLAGS_PREFIX` might be removed in the future
 - change of linking changed size of resulting (stripped) binaries but not drastically so I'm assuming `--gc-sections` with `-lc` do work correctly (new approach was compiled using gcc-9.5 so that might be a big change; I'm a little bit surprised/worried about `test-libc-string` being 10k smaller but it might be connected with gcc-9.5 as the test passes)
   
image

**Comment by nalajcie** [comment]
> * change of linking changed size of resulting (stripped) binaries but not drastically so I'm assuming `--gc-sections` with `-lc` do work correctly (new approach was compiled using gcc-9.5 so that might be a big change; I'm a little bit surprised/worried about `test-libc-string` being 10k smaller but it might be connected with gcc-9.5 as the test passes)

With gcc-9.3 the size changes are more consistent, 10k change was due to new test being added in the mean time
image

**Comment by anglov** [comment]
As far as I can see normally crti.o and crtn.o is delivered by stdlib 
https://gcc.gnu.org/onlinedocs/gccint/Initialization.html

> The prologue of a function (__init) appears in the .init section of crti.o; the epilogue appears in crtn.o. Likewise for the function __fini in the .fini section. Normally these files are provided by the operating system or by the GNU C library, but are provided by GCC for a few targets.

And I see that indeed glibc/newlib/musl have those files

**Comment by nalajcie** [comment]
> As far as I can see normally crti.o and crtn.o is delivered by stdlib https://gcc.gnu.org/onlinedocs/gccint/Initialization.html
> 
> > The prologue of a function (__init) appears in the .init section of crti.o; the epilogue appears in crtn.o. Likewise for the function __fini in the .fini section. Normally these files are provided by the operating system or by the GNU C library, but are provided by GCC for a few targets.
> 
> And I see that indeed glibc/newlib/musl have those files

AFAIK these files are mostly provided by libgcc (side target) as of today. crti.o can be produced in newlib only for really obsolete targets - altrougth newlib still calls _init() as an option:

https://github.com/bminor/newlib/blob/c2d2bf34e6959615a3ba0edf4153d210501ba04f/newlib/libc/misc/init.c#L39-L41

I'll keep it for now, maybe it's only to support legacy software (using _init section instead of constructors), we might remove it in the future (patch to gcc).

**Pull request merged**
