### PR TITLE
Makefile.armv7a: changed getting cpu from TARGET

### PR DESCRIPTION
**Pull request by kemonats**

### CODE REVIEW

**Comment by kemonats** [comment]
A question regarding the error that occurred here when building.
Whether it is really necessary to build `phoenix-rtos-devices` using the `-j` option.

**If not:**
- add `.NOTPARALLEL` to `Makefile`

**if yes:**
1. add dependencies manually
2. change copying `*h` files.

**Comment by nalajcie** [comment]
@MaciejPurski , is this change working in Your setup?

**Comment by MaciejPurski** [comment]
This change works fine, when building for target armv7a7-imx6ull.

**Review by nalajcie — APPROVED** [review]

**Comment by nalajcie** [comment]
@kemonats : regarding the concurrent build, it the cross-component dependencies be solved by introducing explicit PHONY components and writing dependencies between them (currently there is only `all` phony component so no explicit build order is forced). I would try to address it in spare time.

**Pull request merged**
