### PR TITLE
makes: install external headers subtree from "include" dir by default

### PR DESCRIPTION
**Pull request by nalajcie**
## Description
Treat local "include" dir as "external API" - install all include files
in respective subfolders in PREFIX_H. Use local dir for lib/bin
compilation to avoid race conditions when there are cross-header
dependencies present within one component (needed for USB).

Feature enabled by default, to explicitly not install "include" subtree
- set LOCAL_HEADERS_DIR to non-existent directory.
- 
## Motivation and Context
DONE: CI-59

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/180

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
@anglov  please verify it this works for You.
@MaciejPurski IMHO this should solve build races in USB components (if applied there)

**Review by anglov — COMMENTED** [review]
It works fine for me. I don;t check everything, just default one

Important limitation is that you can place only one include $(binary.mk) or include $(static-lib.mk) in one Makefile to not to mess up rules.

Maybe it;s ok – if the component have include dir then it should be self-contain?

**Comment by anglov** [comment]
One more thing, while building lwip that big blob statr to showing:
```
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/sockets_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/nd6_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/altcp_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/memp_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/api_msg.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/tcpip_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/tcp_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/raw_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/memp_std.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/priv/mem_priv.h
HEADER /github/workspace/phoenix-rtos-lwip/lib-lwip/src/include/lwip/ethip6.h
(...)
```

Not sure why and if it's valid

**Comment by nalajcie** [comment]
> Important limitation is that you can place only one include $(binary.mk) or include $(static-lib.mk) in one Makefile to not to mess up rules.

As in the docs - You may specify:
```make
LOCAL_HEADERS_DIR := nothing
```
to avoid automatic install from te `include` dir while building second component.

I'll remove the debug print after investigating if lwip compiles correctly.

**Comment by nalajcie** [comment]
The problem with lwip should be fixed now, details in https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/58

**Review by anglov — APPROVED** [review]
LGTM

**Review by agkaminski — APPROVED** [review]

**Pull request merged**
